---
- import_tasks: pre.yml
- import_tasks: user.yml

- name: Add vimrc to home folder.
  copy:
    src: "files/vimrc"
    dest: "/home/{{ user_name }}/.vimrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"
