"" General
syntax on
set number
set linebreak
set laststatus=2
set noshowmode
set wildmenu

"" Indentation
set autoindent
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4

"" Yaml indentation
autocmd FileType yaml,yml,tf setlocal ts=2 sts=2 sw=2 expandtab

"" Search
set incsearch
set ignorecase
set smartcase
set hlsearch

"" LightLine
if !has('gui_running')
  set t_Co=256
endif

let g:lightline = {
  \ 'colorscheme': 'PaperColor',
  \ 'component_function': {
  \   'gitbranch': 'FugitiveHead'
  \   },
  \ }

"" Colorscheme
let g:PaperColor_Theme_Options = {
  \ 'theme': {
  \   'default': {
  \     'transparent_background': 1
  \     }
  \   }
  \ }

colorscheme PaperColor
set background=dark
