"" General
syntax on
set number
set linebreak
set laststatus=2
set wildmenu
set background=dark

"" Indentation
set autoindent
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4

"" Yaml indentation
autocmd FileType yaml,yml,tf setlocal ts=2 sts=2 sw=2 expandtab

"" Search
set incsearch
set ignorecase
set smartcase
set hlsearch
